services:
 - docker

# We test the latest patch commits of multiple redis versions because sentinel responses are different,
# and to verify that unit tests of redis pass in all of those versions.
env:
 - REDIS_VER=3.0.7
 - REDIS_VER=3.2.13
 - REDIS_VER=4.0.14
 - REDIS_VER=5.0.12
 - REDIS_VER=6.2.1

script: ./travis.sh $REDIS_VER

sudo: required
